name: PHPUnit Tests

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch
    paths:
        - '**.php'
        - 'composer.*'
        - 'phpunit*'
       
  pull_request:
    branches:
      - '*'  # Trigger the workflow on pull requests targeting any branch
    paths:
        - '**.php'
        - 'composer.*'
        - 'phpunit*'
        
jobs:
  run-tests:
    name: Execute PHPUnit Tests
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository content



      - name: Detect framework version change
        run: |
          OLD_VERSION=$(git show HEAD^:Config/Paths.php | grep "public \$systemDirectory" | cut -d '=' -f2 | tr -d " ';")
          NEW_VERSION=$(grep "public \$systemDirectory" Config/Paths.php | cut -d '=' -f2 | tr -d " ';")

          echo "Previous system directory: $OLD_VERSION"
          echo "Current system directory: $NEW_VERSION"

          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "! Framework version changed from $OLD_VERSION to $NEW_VERSION!"
            exit 1
          else
            echo " Framework version is unchanged."
          fi



      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # Set up PHP environment
        with:
          php-version: '8.3.6'  # Define the PHP version
          extensions: mbstring, pdo, pdo_mysql, curl , xdebug # Specify PHP extensions required
          coverage: xdebug  # Configure code coverage (optional)
      - name : Check installed PHP modules
        run: php -m

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --no-suggest  # Install PHP dependencies

      - name: Make PHPUnit executable
        run: chmod +x vendor/bin/phpunit 

      - name: Make bootstrap readable
        run: chmod +r tests/bootstrap.php 

      - name: Run PHPUnit tests
        run: k:/data/CodeIgniter-4.4.5-Shared/vendor/bin/phpunit --configuration phpunit.xml  # Execute PHPUnit tests

        
      - name: Check PHP version and installed extensions
        run: |
          php -v
          php -m  # Optional: List installed PHP modules
